ci(storybook): add upload to github pages using github action

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -36,6 +36,66 @@ jobs:
               env:
                   NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
                   NEXT_PUBLIC_FCM_VAPID_KEY: ${{ secrets.NEXT_PUBLIC_FCM_VAPID_KEY }}
+    build_docs:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout
+              uses: actions/checkout@v3
+            - name: Detect package manager
+              id: detect-package-manager
+              run: |
+                  if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+                  echo "manager=yarn" >> $GITHUB_OUTPUT
+                  echo "command=install" >> $GITHUB_OUTPUT
+                  echo "runner=yarn" >> $GITHUB_OUTPUT
+                  exit 0
+                  elif [ -f "${{ github.workspace }}/package.json" ]; then
+                  echo "manager=npm" >> $GITHUB_OUTPUT
+                  echo "command=ci" >> $GITHUB_OUTPUT
+                  echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+                  exit 0
+                  else
+                  echo "Unable to determine package manager"
+                  exit 1
+                  fi
+            - name: Setup Node
+              uses: actions/setup-node@v3
+              with:
+                  node-version: '16'
+                  cache: ${{ steps.detect-package-manager.outputs.manager }}
+            - name: Setup Pages
+              uses: actions/configure-pages@v3
+            - name: Restore cache
+              uses: actions/cache@v3
+              with:
+                  path: |
+                      .next/cache
+                      # Generate a new cache whenever packages or source files change.
+                  key:
+                      ${{ runner.os }}-storybook-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+                      # If source files changed but packages didn't, rebuild from a prior cache.
+                  restore-keys: |
+                      ${{ runner.os }}-storybook-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+            - name: Install dependencies
+              run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+            - name: Static Storybook Docs
+              run: ${{ steps.detect-package-manager.outputs.runner }} yarn build-storybook
+            - name: Upload artifact
+              uses: actions/upload-pages-artifact@v2
+              with:
+                  path: ./storybook-static
+
+    # Deployment job
+    deploy:
+        environment:
+            name: github-pages
+            url: ${{ steps.deployment.outputs.page_url }}
+        runs-on: ubuntu-latest
+        needs: build_docs
+        steps:
+            - name: Deploy to GitHub Pages
+              id: deployment
+              uses: actions/deploy-pages@v2
     lhci:
         if: github.repository == 'jerensl/www.jerensl.com' && ${{ github.event.label.name == 'need-perf-check' }} && github.event_name == 'pull_request' && github.event.action != 'closed'
         name: Run Lighthouse CI againts Pull Request
